### ISSUE TITLE
Complex property values from data extraction expressions

### ISSUE THREAD

**Issue by vlm---** [datalust/seq-input-healthcheck#10]
Almost every entry in our Seq server has direct or applied properties like Application, Environment, etc. to allow easy filtering. I think it would be a very nice feature to allow users to set applied properties for app instance (exactly like for API keys). It could be even more powerful when values for these properties could be defined as expression and extracted from every endpoint response.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! This is also being discussed in: https://github.com/datalust/seq-tickets/issues/832 - we're keen to make this kind of thing available to all inputs, so we'll probably aim to do this on the Seq side, rather than directly, here.

Regarding expression-based extraction, though - yes, this would be awesome. Currently, array-literal syntax should support `Data` values like `[DB.status, API.status]`, but object-literal syntax, if we could add it to the Seq/_Serilog.Filters.Expressions_ languages, would make this much nicer (e.g. `{DB: DB.status, API: API.status}`)....

I'll leave this ticket open to track the expression possibility; the attached properties case is _almost_ orthogonal to it. Thanks!

**Comment by nblumhardt** [comment]
This now works :+1:
