### ISSUE TITLE
Feature request - option to spread load across the interval

### ISSUE THREAD

**Issue by bigolewannabe** [datalust/seq-input-healthcheck#35]
We've had a couple of times where our large list of health check sites caused a development web server to peg it's CPU. That lead to some time outs that are easy for the people with large page load times to argue isn't there fault b/c when it's not overloaded it's not going to time out. And it's a little hard to argue that it needs more cores when the only time it pegs is when we flood it with health checks.

It would be nice to have an option that spreads out the load by running the health check over the duration of the specified interval instead of in one batch when it's time.

**Comment by liammclennan** [comment]
Hi @bigolewannabe ,

Ideally, your health check input should be something that does not affect the health of your server. Is there a light-weight endpoint you can call that won't place a load on the server?

Otherwise, you can use multiple instances of the health check app to spread out the request timing.

**Comment by nblumhardt** [comment]
Fixed in #37- thanks @bigolewannabe

**Comment by bigolewannabe** [comment]
We just deployed this and excerpt from a elapsed time graph says it all. Thanks for implementation of this!
![image](https://github.com/user-attachments/assets/e1a29240-b1ba-481a-820d-799b95a7deeb)

**Comment by liammclennan** [comment]
That's great. Thanks for letting us know.
